### ISSUE TITLE
setup.bat не может скачать библиотеки svpflow

### ISSUE THREAD

**Issue by DaveScream** [andreiyv/fpska#7]
в батнике указан неактуальный путь для скачивания, утилита не рабочая

**Comment by DaveScream** [comment]
Версия библиотеки поменялась заименил в батнике ссылку для скачивания, скачалось но не смогло распаковаться потому что путь библиотек тоже поменялся, в общем распаковал библиотеки в нужный каталог вручную, но скрипт все равнов ыдает ошибку


Время начала кодирования
23:36:37,62

--------------------------------------------------------
[Шаг 1/5] Извлекаем информацию о видео и аудио кодеках из видеофайла
Информация извлечена успешно в файл "E:\videowork\FPSka\fpska-0.8\tmp\ffprobe.log"

[Шаг 2/5] Извлекаем звуковую дорожку из исходного видеофайла
Звуковая дорожка извлечена успешно

[Шаг 3/5] Создаем скрипт для Vapoursynth из шаблона
*****************************
fpska ne rabotaet s takim fps
*****************************



Traceback (most recent call last):
  File "E:\videowork\FPSka\fpska-0.8\scripts\setfps.py", line 58, in <module>
    line = line.replace("vnm", str(num))
NameError: name 'num' is not defined
Скрипт для Vapoursynth создан успешно

[Шаг 4/5] Создаем видео с частотой 60fps
Текущее количество сконвертированных кадров (frame):
Script evaluation failed:
Python exception: SVSmoothFps: invalid 'params' syntax: * Line 1, Column 16
  Syntax error: value, object or array expected.


Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 1927, in vapoursynth.vpy_evaluateScript
  File "src\cython\vapoursynth.pyx", line 1928, in vapoursynth.vpy_evaluateScript
  File "E:\videowork\FPSka\fpska-0.8\scripts\work.pvy", line 15, in <module>
    smooth = core.svp2.SmoothFps(clip,super["clip"],super["data"],vectors["clip"],vectors["data"],smoothfps_params)
  File "src\cython\vapoursynth.pyx", line 1833, in vapoursynth.Function.__call__
vapoursynth.Error: SVSmoothFps: invalid 'params' syntax: * Line 1, Column 16
  Syntax error: value, object or array expected.


Ошибка создания видео с частотой 60fps
Для продолжения нажмите любую клавишу . . .

**Comment by fgRuslan** [comment]
У меня такая же проблема

**Comment by andreiyv** [comment]
no more relevant
