### ISSUE TITLE
ошибка в setfps.py

### ISSUE THREAD

**Issue by DaveScream** [andreiyv/fpska#8]
видео с моего телефона 29.87 fps    30-29.87 = 0.13

а в скрипте setfps.py макс ошибка 0.1, поэтому вылетает ошибка, нужно исправить

elif abs(float(fps)-30.0) < 0.1:
    num = 2
    den = 1

**Comment by andreiyv** [comment]
Привет, Илья.
Прсото глянь (делать ничего не надо) сможет ли твой алгоритм для num/den справиться с таким видео.
И закрывай это issue.

**Comment by ihujg2346** [comment]
Версия 0.9.1 теперь работает с любым fps меньше 55 (если надо, то можно поменять, но результат не будет заметен)
